### ISSUE TITLE
Fails to create project if command line options are used.

### ISSUE THREAD

**Issue by clamytoe** [MichaelYusko/wizi#23]
Command used: `python -m wiz --name anipy --author 'Martin Uribe' --license_type MIT`
Results: `Error: Got unexpected extra argument (Uribe')`

It works find with just: `python -m wiz`

I believe the issue to be with click, and the easiest fix would be to simply remove the command line flag instructions from your [README.md](https://github.com/MichaelYusko/wizi/blob/master/README.md).

**Comment by MichaelYusko** [comment]
Hello @clamytoe Thanks for the report! Hm, it's weird because, I right now, I ran the command
```python -m wiz --name anipy --author 'Martin Uribe' --license_type MIT``` and all things works fine, I can't reproduce the bug:(

**Comment by clamytoe** [comment]
Perhaps it's a platform thing? I'm using Windows 10 and Anaconda.

**Comment by clamytoe** [comment]
On a hunch I tried the same command but with double quotes around my name and that worked! I think I found a bug with click.

**Comment by clamytoe** [comment]
On a hunch I tried the same command but with double quotes around my name and that worked! I think I found a bug with click.

**Comment by clamytoe** [comment]
Just checked on [click's repo](https://github.com/flosell/trailscraper/issues/11) and it seems to be a built in feature that allows you to send a list of values from the command line and automatically have them separated by a white space.

**Comment by MichaelYusko** [comment]
> On a hunch I tried the same command but with double quotes around my name and that worked! I >think I found a bug with click.
Got it, and seems like, everything is okay?

**Comment by MichaelYusko** [comment]
@clamytoe And will be cool, if you will update the *README* file, for this case.

Anyway, Thx!

**Comment by clamytoe** [comment]
Will do. Master? I noticed that develop is behind.

**Comment by MichaelYusko** [comment]
@clamytoe Thank you, yes, first you need to make a PR into ```develop``` branch.
